import SwiftUI

// MARK: - HomeTasksView

/// Parent-facing home tasks screen. Shows tasks generated by LLM after each session.
struct HomeTasksView: View {
    @Environment(AppContainer.self) private var container
    @State private var tasks: [HomeTask] = HomeTask.sampleTasks
    @State private var isLoading: Bool = false

    var body: some View {
        NavigationStack {
            Group {
                if isLoading {
                    HSLoadingView(message: "Загрузка заданий...")
                } else if tasks.isEmpty {
                    HSEmptyStateView(
                        icon: "checkmark.circle",
                        title: "Заданий пока нет",
                        message: "Завершите занятие — и здесь появятся домашние задания"
                    )
                } else {
                    List(tasks) { task in
                        HomeTaskRow(task: task, onToggle: { toggleTask(task) })
                    }
                    .listStyle(.insetGrouped)
                }
            }
            .navigationTitle("Домашние задания")
        }
    }

    private func toggleTask(_ task: HomeTask) {
        if let idx = tasks.firstIndex(where: { $0.id == task.id }) {
            tasks[idx].isCompleted.toggle()
        }
    }
}

// MARK: - HomeTask Model

struct HomeTask: Identifiable {
    let id: String
    let soundTarget: String
    let description: String
    let wordExamples: [String]
    var isCompleted: Bool
    let durationMinutes: Int

    static let sampleTasks: [HomeTask] = [
        HomeTask(id: "1", soundTarget: "Р", description: "Повторите слова со звуком Р",
                 wordExamples: ["рыба", "рука", "дерево"], isCompleted: false, durationMinutes: 5),
        HomeTask(id: "2", soundTarget: "Р", description: "Прочитайте стихотворение про рыбку",
                 wordExamples: [], isCompleted: false, durationMinutes: 3)
    ]
}

// MARK: - HomeTaskRow

private struct HomeTaskRow: View {
    let task: HomeTask
    let onToggle: () -> Void

    var body: some View {
        HStack(alignment: .top, spacing: SpacingTokens.medium) {
            Button(action: onToggle) {
                Image(systemName: task.isCompleted ? "checkmark.circle.fill" : "circle")
                    .font(.title2)
                    .foregroundStyle(task.isCompleted ? .green : .secondary)
            }
            .buttonStyle(.plain)

            VStack(alignment: .leading, spacing: SpacingTokens.tiny) {
                HStack {
                    Text(task.soundTarget)
                        .font(TypographyTokens.caption())
                        .padding(.horizontal, 8)
                        .padding(.vertical, 2)
                        .background(ColorTokens.Brand.primary.opacity(0.15))
                        .foregroundStyle(ColorTokens.Brand.primary)
                        .clipShape(Capsule())
                    Spacer()
                    Label("\(task.durationMinutes) мин", systemImage: "clock")
                        .font(TypographyTokens.caption())
                        .foregroundStyle(.secondary)
                }
                Text(task.description)
                    .font(TypographyTokens.body())
                    .strikethrough(task.isCompleted)

                if !task.wordExamples.isEmpty {
                    Text(task.wordExamples.joined(separator: " · "))
                        .font(TypographyTokens.caption())
                        .foregroundStyle(.secondary)
                }
            }
        }
        .padding(.vertical, SpacingTokens.tiny)
    }
}
